apiVersion: v1
kind: Service
metadata:
  name: olivetti-service
spec:
  type: LoadBalancer   # or NodePort if cloud provider does not support LB
  selector:
    app: olivetti
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
